### ISSUE TITLE
browser had updates

### ISSUE THREAD

**Issue by coffee614614** [suryakant261/StalkOnWhatsapp#1]
I use firefox and browser had updates and i updated... then i cannot paste your code into the console screen... can you help ?

**Comment by suryakant261** [comment]
Are you unable to open developer's console ? Or is it not allowing pasting but allowing typing?

Alternatively you can bookmark the script as mentioned in the documentation.

**Comment by coffee614614** [comment]
Can you email me at ***@***.***

I used Microsoft Edge and it works... but Firefox doesn't... I don't
understand how you bookmark the script, I opened "add a bookmark", copy and
paste your script onto URL in firefox and it won't save... do you have
screenshots ?

**Comment by suryakant261** [comment]
Hi @coffee614614 ,

You email address in the above comment is masked and i can't really see it. Please go through the documentation of the browser you are using to understand bookmark creation and enabling bookmark bar.

If you still see issues, feel free to reach out to me via links mentioned in the readme.

**Comment by coffee614614** [comment]
misshaeh[at] g m a i l [dot] c o m

I need to keep your contact, cause whatsapp or the browser will update from
time to time and your script probably needs some changes too.

Can you send screenshot how to put the script in the bookmark ?

**Comment by suryakant261** [comment]
emailed you from pd . skant @ g m a i l . c o m
